services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: defisys-backend
    ports:
      - "8000:8000"
    environment:
      PYTHONDONTWRITEBYTECODE: "1"
      PYTHONUNBUFFERED: "1"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: defisys-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      APP_BACKEND_URL: "http://backend:8000"